<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>Ultimate294</AssemblyName>
    <RootNamespace>SCP294</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Deterministic>true</Deterministic>
    <Version>2.1.0</Version>
    <SLReferences Condition="'$(SLReferences)' == ''">$(MSBuildThisFileDirectory)references</SLReferences>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="$(SLReferences)/*.dll" Private="false" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Compile Include="Classes/DrinkManager.cs" />
    <Compile Include="Classes/OpusComponent.cs" />
    <Compile Include="Classes/SCP294Object.cs" />
    <Compile Include="Classes/SoundHandler.cs" />
    <Compile Include="Commands/SCP294AdminCommand.cs" />
    <Compile Include="Commands/SCP294Command.cs" />
    <Compile Include="Config.cs" />
    <Compile Include="Handlers/playerHandler.cs" />
    <Compile Include="Handlers/serverHandler.cs" />
    <Compile Include="Patches/OnEffectsApplied.cs" />
    <Compile Include="SCP294.cs" />
    <Compile Include="ServerSpecificSettings.cs" />
    <Compile Include="Types/Config/CustomDrink.cs" />
    <Compile Include="Types/Config/DrinkCallbacks.cs" />
    <Compile Include="Types/Config/DrinkEffect.cs" />
    <Compile Include="Types/Config/DrinkList.cs" />
    <Compile Include="Types/Config/SpawningConfig.cs" />
    <Compile Include="Types/Config/SpawnTransform.cs" />
    <Compile Include="Types/DrinkInfo.cs" />
    <Compile Include="Types/DrinkSound.cs" />
    <Compile Include="Utils/RoomHandler.cs" />
    <Compile Include="Properties/AssemblyInfo.cs" />
  </ItemGroup>
</Project>